language: go

branches:
  only:
    - master

matrix:
  include:
    - go: 1.7.6
    - go: 1.8
    - go: 1.9

before_script:
  - go vet ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -race

# CODECOV_TOKEN set in travis ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)
